<?php
require '../../../../db.php';
require '../../../../validarAcceso.php';
if ($_SERVER['REQUEST_METHOD'] === 'POST' && isset($_POST['id_cuenta_accion'], $_POST['nuevo_estado'])) {
    $stmt = $pdo->prepare('UPDATE Cuenta SET id_EstadoCuenta = :estado WHERE id_cuenta = :id_cuenta AND id_tipoCuenta = 1');
    $stmt->execute([':estado' => (int) $_POST['nuevo_estado'], ':id_cuenta' => (int) $_POST['id_cuenta_accion']]);
    header('Location: huesped_habilitarInhabilitar.php');
    exit;
}
$busqueda = trim($_GET['busqueda'] ?? '');
$stmt = $pdo->prepare('SELECT C.id_cuenta, C.correo_cuenta, C.id_EstadoCuenta, H.dni_huesped, H.nombre_huesped, H.apellido_huesped FROM Cuenta C INNER JOIN Huesped H ON C.id_cuenta = H.id_cuenta WHERE C.id_tipoCuenta = 1 AND (C.correo_cuenta LIKE :busqueda OR H.dni_huesped LIKE :busqueda OR H.nombre_huesped LIKE :busqueda OR H.apellido_huesped LIKE :busqueda) ORDER BY H.apellido_huesped, H.nombre_huesped');
$stmt->execute([':busqueda' => '%' . $busqueda . '%']);
$huespedes = $stmt->fetchAll(PDO::FETCH_ASSOC);
?>
<!DOCTYPE html>
<html lang="es"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Habilitar o Inhabilitar Huésped</title><script src="https://cdn.tailwindcss.com"></script></head>
<body class="bg-gray-50 min-h-screen flex flex-col m-0"><div class="w-full"><?php require '../../../../barraNav.php'; ?></div><div class="w-full px-4 pt-4"><a href="../../area_huesped.php" class="inline-block bg-gray-200 hover:bg-gray-300 text-gray-700 font-semibold py-3 px-6 rounded-lg">&larr; Regresar al área de huéspedes</a></div>
<main class="max-w-6xl mx-auto w-full px-4 py-10 space-y-6"><div class="flex flex-col md:flex-row justify-between items-center bg-white p-6 rounded-xl shadow-md gap-4"><h1 class="text-2xl font-bold text-gray-800">Huéspedes</h1><form method="GET" class="flex w-full md:w-auto gap-2"><input type="text" name="busqueda" value="<?php echo htmlspecialchars($busqueda); ?>" placeholder="Buscar huésped..." class="border border-gray-300 rounded-lg px-4 py-2 w-full md:w-72"><button type="submit" class="bg-blue-600 text-white font-semibold px-4 py-2 rounded-lg">Buscar</button><?php if ($busqueda !== ''): ?><a href="huesped_habilitarInhabilitar.php" class="bg-gray-200 px-3 py-2 rounded-lg">Limpiar</a><?php endif; ?></form></div>
<div class="bg-white rounded-xl shadow-md overflow-hidden"><div class="overflow-x-auto"><table class="w-full text-left"><thead><tr class="bg-gray-100 text-gray-700 text-sm uppercase"><th class="py-3 px-6">Huésped</th><th class="py-3 px-6">DNI</th><th class="py-3 px-6">Correo</th><th class="py-3 px-6 text-center">Estado</th><th class="py-3 px-6 text-center">Acción</th></tr></thead><tbody class="divide-y divide-gray-200 text-sm"><?php if ($huespedes): foreach ($huespedes as $huesped): ?><tr><td class="py-4 px-6 font-medium"><?php echo htmlspecialchars($huesped['nombre_huesped'] . ' ' . $huesped['apellido_huesped']); ?></td><td class="py-4 px-6"><?php echo htmlspecialchars($huesped['dni_huesped']); ?></td><td class="py-4 px-6"><?php echo htmlspecialchars($huesped['correo_cuenta']); ?></td><td class="py-4 px-6 text-center"><?php if ((int) $huesped['id_EstadoCuenta'] === 1): ?><span class="text-green-700">Habilitado</span><?php else: ?><span class="text-red-700">Inhabilitado</span><?php endif; ?></td><td class="py-4 px-6 text-center"><form method="POST"><input type="hidden" name="id_cuenta_accion" value="<?php echo (int) $huesped['id_cuenta']; ?>"><?php if ((int) $huesped['id_EstadoCuenta'] === 1): ?><input type="hidden" name="nuevo_estado" value="2"><button class="bg-red-600 text-white px-4 py-1 rounded-lg">Inhabilitar</button><?php else: ?><input type="hidden" name="nuevo_estado" value="1"><button class="bg-green-600 text-white px-4 py-1 rounded-lg">Habilitar</button><?php endif; ?></form></td></tr><?php endforeach; else: ?><tr><td colspan="5" class="py-6 text-center text-gray-500">No se encontraron huéspedes.</td></tr><?php endif; ?></tbody></table></div></div></main></body></html>
